#!/usr/bin/env bash

set -e

# development environment
#nix develop

# Cleanup
rm vyasa.img rootfs bash-5.2.37 coreutils-9.6 glibc-2.40 linux ncurses-6.5 util-linux-2.40.4 -rfd

# Rootfs dirs
export WS=$(pwd)
export VYASA=$(pwd)/rootfs

mkdir rootfs/{boot,proc,sys,dev,usr} -p
mkdir rootfs/usr/{lib,lib64,bin,sbin} -p
cd rootfs/
ln -s usr/bin bin
ln -s usr/sbin sbin
ln -s usr/lib lib
ln -s usr/lib64 lib64
cd ..


# Kernel
tar -xf linux-6.13.5.tar.zst

cd linux
make tinyconfig

# Kernel config

./scripts/config --set-val CONFIG_64BIT y
./scripts/config --set-val CONFIG_X86_64 y

./scripts/config --set-val CONFIG_BLOCK y
./scripts/config --set-val CONFIG_VIRTIO_BLK y
./scripts/config --set-val CONFIG_VIRTIO_PCI y

./scripts/config --set-val CONFIG_SATA_AHCI_PLATFORM y

./scripts/config --set-val CONFIG_BINFMT_ELF y
./scripts/config --set-val CONFIG_BINFMT_SCRIPT y

./scripts/config --set-val CONFIG_PRINTK y

./scripts/config --set-val CONFIG_DEVTMPFS y
./scripts/config --set-val CONFIG_DEVTMPFS_MOUNT y

./scripts/config --set-val CONFIG_PCI y
./scripts/config --set-val CONFIG_TTY y
./scripts/config --set-val CONFIG_SERIAL_8250 y
./scripts/config --set-val CONFIG_SERIAL_8250_CONSOLE y

./scripts/config --set-val CONFIG_SCSI y
./scripts/config --set-val CONFIG_BLK_DEV_SD y

./scripts/config --set-val CONFIG_ATA y
./scripts/config --set-val CONFIG_ATA_PIIX y
./scripts/config --set-val CONFIG_SATA_HOST y

./scripts/config --set-val CONFIG_EXT4_FS y
./scripts/config --set-val CONFIG_VFAT_FS y

./scripts/config --set-val CONFIG_PROC_FS y
./scripts/config --set-val CONFIG_SYSFS y

#Other options
./scripts/config --set-val CONFIG_GENERIC_CPU y


#make oldconfig
#make olddefconfig
make defconfig

make -j16
cp arch/x86/boot/bzImage $VYASA/boot/
cd $WS

# Bash
tar -xf bash-5.2.37.tar.gz
mkdir bash-5.2.37/build -p
cd bash-5.2.37/build
../configure --prefix=/usr

make -j16
make DESTDIR=$VYASA install
cd $WS

# Coreutils
tar -xf coreutils-9.6.tar.xz
mkdir coreutils-9.6/build -p
cd coreutils-9.6/build
export FORCE_UNSAFE_CONFIGURE=1 # error: you should not run configure as root
../configure --without-selinux --disable-libcap --prefix=/usr

make -j16
make DESTDIR=$VYASA install
cd $WS

# Util-linux
tar -xf util-linux-2.40.4.tar.xz
mkdir util-linux-2.40.4/build -p
cd util-linux-2.40.4
./autogen.sh
cd build
../configure --disable-liblastlog2 --prefix=/usr

make -j16
make DESTDIR=$VYASA install
cd $WS


# Glibc
tar -xf glibc-2.40.tar.xz
mkdir glibc-2.40/build -p
cd glibc-2.40/build
../configure --disable-werror --libdir=/lib --prefix=/usr

make -j16
make DESTDIR=$VYASA install
#CFLAGS="-U_FORTIFY_SOURCE -O2 -fno-stack-protector" make -j16
cd $WS


# ncurses
tar -xf ncurses-6.5.tar.gz
mkdir ncurses-6.5/build -p
cd ncurses-6.5/build
../configure --disable-werror --libdir=/lib --prefix=/usr

make -j16
make DESTDIR=$VYASA install
cd $WS


# LD
$VYASA/bin/ld.so --help # check
echo "/usr/lib" > $VYASA/etc/ld.so.config
echo "/usr/lib64" >> $VYASA/etc/ld.so.config

# init
cat > "$VYASA"/sbin/init << 'EOF' &&
#!/bin/bash

mount -t proc none /proc
mount -t sysfs none /sys

/bin/bash
EOF
chmod +x "$VYASA"/sbin/init

# fdisk
cd $WS
dd if=/dev/zero of=vyasa.img bs=1M count=1024
fdisk vyasa.img <<EOF
n
p
1


a
w
EOF


#####################################
#          flaky section
#####################################
mkdir /tmp/mnt
ldev=$(losetup -fP --show vyasa.img)
mkfs.ext4 "$ldev"p1
mount "$ldev"p1 /tmp/mnt
cp -R $VYASA/* /tmp/mnt/

#grub
#grub-install --target=i386-pc --root-directory=/tmp/mnt --no-floppy --modules="normal part_msdos ext2 multiboot" $ldev
grub-install --target=i386-pc --root-directory=/tmp/mnt --no-floppy --modules="normal part_msdos ext2 multiboot" $ldev --force
#doas nix shell nixpkgs#grub2 -c grub-install --target=i386-pc --root-directory=/tmp/mnt --no-floppy --modules="normal part_msdos ext2 multiboot" /dev/loop0

#####################################

cat > /tmp/mnt/boot/grub/grub.cfg <<EOF
menuentry 'Vyasa' {
    set root='(hd0,1)'
    linux /boot/bzImage root=/dev/sda1 rw
}
EOF


sync
sync
sync
umount /tmp/mnt
losetup -d $ldev
sync
sync
sync


exit 0
