#!/bin/sh

set -e -u -o pipefail

# gettext
# ------------------------------
cd /builds
rm -rf gettext-0.22
tar -xf /sources/gettext-0.22.tar.xz
mkdir gettext-0.22/build -p
cd gettext-0.22/build

../configure --disable-shared

make -j$(nproc)

#make install
cp -v gettext-tools/src/{msgfmt,msgmerge,xgettext} /usr/bin # install limited programs
# ------------------------------

