#!/bin/sh

set -e -u -o pipefail

# perl
# ------------------------------
cd /builds
rm -rf perl-5.40.1
tar -xf /sources/perl-5.40.1.tar.gz
cd perl-5.40.1
sh ./Configure -des                                      \
             -D prefix=/usr                               \
             -D vendorprefix=/usr                         \
             -D useshrplib                                \
             -D privlib=/usr/lib/perl5/5.40/core_perl     \
             -D archlib=/usr/lib/perl5/5.40/core_perl     \
             -D sitelib=/usr/lib/perl5/5.40/site_perl     \
             -D sitearch=/usr/lib/perl5/5.40/site_perl    \
             -D vendorlib=/usr/lib/perl5/5.40/vendor_perl \
             -D vendorarch=/usr/lib/perl5/5.40/vendor_perl

make -j$(nproc)

make install
# ------------------------------
