#!/bin/sh

set -e -u -o pipefail

# util-linux
# ------------------------------
cd /builds
rm -rf util-linux-2.40.4
tar -xf /sources/util-linux-2.40.4.tar.xz
mkdir util-linux-2.40.4/build -p
cd util-linux-2.40.4/build

mkdir -pv /var/lib/hwclock
../configure --libdir=/usr/lib     \
            --runstatedir=/run    \
            --disable-chfn-chsh   \
            --disable-login       \
            --disable-nologin     \
            --disable-su          \
            --disable-setpriv     \
            --disable-runuser     \
            --disable-pylibmount  \
            --disable-static      \
            --disable-liblastlog2 \
            --without-python      \
            ADJTIME_PATH=/var/lib/hwclock/adjtime \
            --docdir=/usr/share/doc/util-linux-2.40.4
make -j$(nproc)

make install
# ------------------------------
