#!/bin/sh

set -e -u -o pipefail

###################################################
# Stage 1 from cross compiler

# gcc-patch
# ------------------------------
# ❯ ./contrib/download_prerequisites
# http://gcc.gnu.org/pub/gcc/infrastructure/isl-0.24.tar.bz2
# ❯ ll vbuilds/gcc-14.2.0/{gettext-0.22.tar.gz,gmp-6.2.1.tar.bz2,isl-0.24.tar.bz2,mpc-1.2.1.tar.gz,mpfr-4.1.0.tar.bz2}
cd $WS/builds
tar -xf ../sources/gcc-14.2.0.tar.xz

cd gcc-14.2.0

tar -xf ../../sources/mpfr-4.1.0.tar.xz
mv -v mpfr-4.1.0 mpfr
tar -xf ../../sources/gmp-6.3.0.tar.xz
mv -v gmp-6.3.0 gmp
tar -xf ../../sources/mpc-1.2.1.tar.gz
mv -v mpc-1.2.1 mpc
tar -xf ../../sources/isl-0.24.tar.bz2
mv -v isl-0.24 isl

sed -e '/m64=/s/lib64/lib/' -i.orig gcc/config/i386/t-linux64

cd $WS/builds

mkdir gcc-14.2.0/sbuild -p

cd gcc-14.2.0/sbuild

../configure                    \
    --prefix=$VYASA/tools       \
    --with-sysroot=$VYASA       \
    --target=$VYASA_TGT         \
    --with-glibc-version=2.41   \
    --with-newlib             \
    --without-headers         \
    --enable-default-pie      \
    --enable-default-ssp      \
    --disable-nls             \
    --disable-shared          \
    --disable-multilib        \
    --disable-threads         \
    --disable-libatomic       \
    --disable-libgomp         \
    --disable-libquadmath     \
    --disable-libssp          \
    --disable-libvtv          \
    --disable-libstdcxx       \
    --enable-languages=c,c++

make -j$(nproc)
make install
cd ..
cat gcc/limitx.h gcc/glimits.h gcc/limity.h > `dirname $($VYASA/tools/bin/$VYASA_TGT-gcc -print-libgcc-file-name)`/include/limits.h
#bash fixincludes/mkheaders
# ------------------------------

