#!/bin/sh

set -e -u -o pipefail

# grep
# ------------------------------
cd $WS/builds
tar -xf ../sources/grep-3.11.tar.xz
mkdir grep-3.11/build -p
cd grep-3.11/build

../configure --prefix=/usr   \
            --host=$VYASA_TGT \
            --build=$(../build-aux/config.guess)

make -j$(nproc)

make DESTDIR=$VYASA install
cd .. && package $(basename `pwd`)
# ------------------------------

