#!/bin/sh

set -e -u -o pipefail

# tar
# ------------------------------
cd $WS/builds
tar -xf ../sources/tar-1.35.tar.xz
mkdir tar-1.35/build -p
cd tar-1.35/build

../configure --prefix=/usr   \
            --host=$VYASA_TGT \
            --build=$(../build-aux/config.guess)

make -j$(nproc)

make DESTDIR=$VYASA install
# ------------------------------

