#!/bin/sh

set -e -u -o pipefail

# target libstdc++
# ------------------------------
cd $WS/builds
mkdir gcc-14.2.0/libstdc++-v3/sbuild -p
cd gcc-14.2.0/libstdc++-v3/sbuild

../configure                        \
    --host=$VYASA_TGT               \
    --build=$(../../config.guess)   \
    --prefix=/usr                   \
    --disable-multilib              \
    --disable-nls                   \
    --disable-libstdcxx-pch         \
    --enable-libstdcxx-threads=no   \
    --with-libstdcxx-zoneinfo=no    \
    --with-gxx-include-dir=/tools/$VYASA_TGT/include/c++/14.2.0

make -j$(nproc)
make DESTDIR=$VYASA install
rm -vf $VYASA/usr/lib/lib{stdc++{,exp,fs},supc++}.la
# ------------------------------

