#!/bin/sh

set -e -u -o pipefail

# Glibc
# ------------------------------

# for standard only
mkdir $VYASA/lib64
ln -sfv ../lib/ld-linux-x86-64.so.2 $VYASA/lib64
ln -sfv ../lib/ld-linux-x86-64.so.2 $VYASA/lib64/ld-lsb-x86-64.so.3

cd $WS/builds
tar -xf ../sources/glibc-2.41.tar.xz
mkdir glibc-2.41/sbuild -p
cd glibc-2.41
echo "rootsbindir=/usr/sbin" > configparms
cd sbuild

export CFLAGS="-Wno-error -Wno-error=implicit-function-declaration -Wno-error=format-security"
export CXXFLAGS="-Wno-error -Wno-error=implicit-function-declaration -Wno-error=format-security"
export CPPFLAGS="-Wno-error -Wno-error=implicit-function-declaration -Wno-error=format-security"
#[-Werror=format-security]
#[-Werror=attributes]

../configure                    \
    --prefix=/usr               \
    --host=$VYASA_TGT           \
    --build=$(../scripts/config.guess) \
    --enable-kernel=5.4                \
    --with-headers=$VYASA/usr/include    \
    --disable-nscd                     \
    libc_cv_slibdir=/usr/lib

make -j$(nproc)
make DESTDIR=$VYASA install
sed '/RTLDLIST=/s@/usr@@g' -i $VYASA/usr/bin/ldd
# ------------------------------
