#!/bin/sh

set -e -u -o pipefail

# Kernel
# ------------------------------
cd $WS/builds
tar -xf ../sources/linux-6.14.4.tar.xz

cd linux-6.14.4
make mrproper

make headers
find usr/include -type f ! -name '*.h' -delete
cp -rv usr/include $VYASA/usr
# ------------------------------

