#!/usr/bin/env bash

set -e -u -o pipefail

# development environment
#nix develop

RUNAS="" # "" or doas or sudo

#https://www.shellhacks.com/bash-colors/
#❯ neofetch
# fg = 30..37
# bg = 40..47
# lfg = 1;{30..37}
# lbg = 1;{40..47}

# MODIFICATIONS: 0 -> Normal, 1 -> Bold, 4 -> Underline, 5 -> Blinking, 7 -> Reverse video char
# -e    	Enable interpretation of backslash escapes
# \e[   	Begin the color modifications
# COLORm	Color Code + ‘m’ at the end
# \e[0m 	End code in the color modifications
#
# echo -e "\e[COLORmSample Text\e[0m"
# echo -e "\e[COLOR1;COLOR2mSample Text\e[0m"

echo -e "\e[1;34mBuilding Vyasa linux....\e[0m"

# Warmup admin
$RUNAS echo -e "\e[1;36m$(uname -a)\e[0m"

# Cleanup
SECONDS=0
TOTALTIME=0

$RUNAS rm vyasa.qcow2 builds rootfs disk -rfd
#$RUNAS rm vyasa.qcow2 builds rootfs disk toolchains -rfd

WS=$(pwd)
mkdir -p $WS/builds
VYASA=$(pwd)/rootfs
VYASA_TGT=$(uname -m)-vyasa-linux-gnu

export WS VYASA VYASA_TGT
echo "--------------------------------" > timings.txt
echo ":: Timing :: package :: duration" >> timings.txt
echo "----------- Toolchain ----------" >> timings.txt

for pack in fhs init binutils gcc kernel-headers glibc check cpp;
do
    echo $pack
    echo -e "\e[1;34m\nInstalling $pack ....\n\e[0m"

    bash -e ./scripts/base/$pack
    
duration=$SECONDS
echo -e "\e[1;33m$pack took: $((duration / 60)) minutes and $((duration % 60)) seconds elapsed.\e[0m"
echo ":: $duration :: $pack :: took $((duration / 60)) minutes and $((duration % 60)) seconds." >> timings.txt
TOTALTIME=$((TOTALTIME + duration))
SECONDS=0
done

# DEBUG:
#cp /tmp/nxjs/{ash,dash,rldd} $VYASA/bin/

###################################################
PATH=$PATH:$VYASA/usr/bin:$VYASA/tools/bin
#TOOL="$VYASA_TGT"-
#CC="$TOOL"gcc
#CXX="$TOOL"g++
#MAKE=$(which make)

export WS VYASA VYASA_TGT PATH
echo "--------------------------------" >> timings.txt
echo ":: Timing :: package :: duration" >> timings.txt
echo "---------- Temp Tools ----------" >> timings.txt

for pack in m4 ncurses bash coreutils diffutils file findutils gawk grep gzip make patch sed tar xz binutils gcc-patch gcc;
do
    echo $pack
    echo -e "\e[1;34m\nInstalling $pack ....\n\e[0m"

    bash -e ./scripts/ttls/$pack
    
duration=$SECONDS
echo -e "\e[1;33m$pack took: $((duration / 60)) minutes and $((duration % 60)) seconds elapsed.\e[0m"
echo ":: $duration :: $pack :: took $((duration / 60)) minutes and $((duration % 60)) seconds." >> timings.txt
TOTALTIME=$((TOTALTIME + duration))
SECONDS=0
done

echo -e "\e[1;36mTotal time took: $((TOTALTIME / 60)) minutes and $((TOTALTIME % 60)) seconds elapsed.\e[0m"
exit 0
