#!/bin/sh

set -e -u -o pipefail

# bzip
# ------------------------------
cd /builds
rm -rf bzip2-1.0.8
tar -xf /sources/bzip2-1.0.8.tar.gz
cd bzip2-1.0.8

make -f Makefile-libbz2_so
make clean


make -j$(nproc)

make PREFIX=/usr install

cp -av libbz2.so.* /usr/lib
ln -sv libbz2.so.1.0.8 /usr/lib/libbz2.so

cp -v bzip2-shared /usr/bin/bzip2
for i in /usr/bin/{bzcat,bunzip2}; do
  ln -sfv bzip2 $i
done
#FIX:package $(basename `pwd`)
# ----------------------------
