#!/bin/sh

set -e -u -o pipefail

# dnsmasq2
# ------------------------------
cd /builds
rm -rf dnsmasq-2.90
tar -xf /sources/dnsmasq-2.90.tar.xz
cd dnsmasq-2.90
make -j$(nproc)
cp src/dnsmasq /bin
make install
# ------------------------------
