#!/bin/sh

set -e -u -o pipefail

# xz
# ------------------------------
cd /builds
rm -rf file-5.46
tar -xf /sources/file-5.46.tar.gz
mkdir file-5.46/build -p
cd file-5.46/build

../configure --prefix=/usr

make -j16
make install
# ------------------------------
