#!/bin/sh

set -e -u -o pipefail

# flex
# ------------------------------
cd /builds
rm -rf flex-2.6.4
tar -xf /sources/flex-2.6.4.tar.gz

cp /sources/config.guess flex-2.6.4/build-aux/
cp /sources/config.sub flex-2.6.4/build-aux/

mkdir flex-2.6.4/build -p
cd flex-2.6.4/build

../configure --prefix=/usr \
            --docdir=/usr/share/doc/flex-2.6.4 \
            --disable-static

make -j$(nproc)
make install
cd .. && package $(basename `pwd`)
# ------------------------------
