#!/bin/sh

set -e -u -o pipefail

# Glibc
# ------------------------------
cd /builds
rm -rf glibc-2.41
tar -xf /sources/glibc-2.41.tar.xz
mkdir glibc-2.41/build -p
echo "rootsbindir=/usr/sbin" > configparms
cd glibc-2.41/build

../configure --prefix=/usr                            \
             --disable-werror                         \
             --enable-kernel=5.4                      \
             --enable-stack-protector=strong          \
             --disable-nscd                           \
             libc_cv_slibdir=/usr/lib

make -j16

touch /etc/ld.so.conf
sed '/test-installation/s@$(PERL)@echo not running@' -i ../Makefile

make install

sed '/RTLDLIST=/s@/usr@@g' -i /usr/bin/ldd

localedef -i C -f UTF-8 C.UTF-8
localedef -i en_US -f UTF-8 en_US.UTF-8
localedef -i te_IN -f UTF-8 te_IN.UTF-8

make localedata/install-locales

tar -xf /sources/tzdata2025a.tar.gz
ZONEINFO=/usr/share/zoneinfo
mkdir -pv $ZONEINFO/{posix,right}
for tz in etcetera southamerica northamerica europe africa antarctica  \
          asia australasia backward; do
    zic -L /dev/null   -d $ZONEINFO       ${tz}
    zic -L /dev/null   -d $ZONEINFO/posix ${tz}
    zic -L leapseconds -d $ZONEINFO/right ${tz}
done
cp -v zone.tab zone1970.tab iso3166.tab $ZONEINFO
zic -d $ZONEINFO -p America/New_York
unset ZONEINFO tz

tee -a /etc/nsswitch.conf > /dev/null <<EOF
# Begin /etc/nsswitch.conf
passwd: files
group: files
shadow: files
hosts: files dns
networks: files
protocols: files
services: files
ethers: files
rpc: files
# End /etc/nsswitch.conf
EOF

mkdir -pv /etc/ld.so.conf.d
tee -a /etc/ld.so.config > /dev/null <<EOF
/lib
/lib64
/usr/lib
/usr/lib64
/usr/local/lib
/usr/local/lib64
/opt/lib
include /etc/ld.so.conf.d/*.conf
EOF


TIMEZONE=$(tzselect)
ln -sfv /usr/share/zoneinfo/"$TIMEZONE" /etc/localtime

# ------------------------------

