#!/bin/sh

set -e -u -o pipefail

# iana
# ------------------------------
cd /builds
rm -rf iana-etc-20250311
tar -xf /sources/iana-etc-20250311.tar.gz

cd iana-etc-20250311

cp services protocols /etc
# ------------------------------

