#!/bin/sh

set -e -u -o pipefail

# iproute - deps: elfutils, libcap, libz, libzstd
# ------------------------------
cd /builds
rm -rf iproute2-6.13.0
tar -xf /sources/iproute2-6.13.0.tar.xz

cd iproute2-6.13.0
./configure --libbpf_force off --prefix=/usr

make -j$(nproc)
make install
# ------------------------------
