#!/bin/sh

set -e -u -o pipefail

# libcap
# ------------------------------
cd /builds
rm -rf libcap-2.75
tar -xf /sources/libcap-2.75.tar.gz
cd libcap-2.75

make -j$(nproc)
make install
# ------------------------------
