#!/bin/sh

set -e -u -o pipefail

# m4
# ------------------------------
cd /builds
rm -rf m4-1.4.19
tar -xf /sources/m4-1.4.19.tar.xz
mkdir m4-1.4.19/build -p
cd m4-1.4.19/build

../configure --prefix=/usr

make -j$(nproc)
make install
# ------------------------------
