#!/bin/sh

set -e -u -o pipefail

# nano
# ------------------------------
cd /builds
rm -rf nano-8.3
tar -xf /sources/nano-8.3.tar.xz
mkdir nano-8.3/build -p
cd nano-8.3/build

../configure --prefix=/usr 

make -j16
make install
# ------------------------------

