#!/bin/sh

set -e -u -o pipefail

# Ncurses
# ------------------------------
cd /builds

rm -rf /nix

rm -rf ncurses-6.5
tar -xf /sources/ncurses-6.5.tar.gz

mkdir ncurses-6.5/build -p
cd ncurses-6.5/build

 ../configure --prefix=/usr           \
            --mandir=/usr/share/man \
            --with-shared           \
            --without-debug         \
            --without-normal        \
            --with-cxx-shared       \
            --enable-pc-files       \
            --with-pkg-config-libdir=/usr/lib/pkgconfig

make -j$(nproc)

make install
ln -sfv libncursesw.so /usr/lib/libncurses.so
cd .. && package $(basename `pwd`)
# ------------------------------
