#!/bin/sh

set -e -u -o pipefail

# openssl
# ------------------------------
cd /builds
rm -rf openssl-3.4.1
tar -xf /sources/openssl-3.4.1.tar.gz
mkdir openssl-3.4.1/build -p
cd openssl-3.4.1/build

../config --prefix=/usr         \
         --openssldir=/etc/ssl \
         --libdir=lib          \
         shared                \
         zlib-dynamic

make -j$(nproc)
sed -i '/INSTALL_LIBS/s/libcrypto.a libssl.a//' Makefile

make MANSUFFIX=ssl install
cd .. && package $(basename `pwd`)
# ------------------------------
