#!/bin/sh

set -e -u -o pipefail

# readline
# ------------------------------
cd /builds
rm -rf readline-8.2.13
tar -xf /sources/readline-8.2.13.tar.gz
mkdir readline-8.2.13/build -p

cd readline-8.2.13
sed -i '/MV.*old/d' Makefile.in
sed -i '/{OLDSUFF}/c:' support/shlib-install

sed -i 's/-Wl,-rpath,[^ ]*//' support/shobj-conf

cd build

../configure --prefix=/usr    \
            --disable-static \
            --with-curses    \
            --docdir=/usr/share/doc/readline-8.2.13

make SHLIB_LIBS="-lncursesw" -j$(nproc)
make install
cd .. && package $(basename `pwd`)
# ------------------------------
