#!/bin/sh

set -e -u -o pipefail

# wget
# ------------------------------
cd /builds
rm -rf wget-1.25.0
tar -xf /sources/wget-1.25.0.tar.gz
mkdir wget-1.25.0/build -p
cd wget-1.25.0/build
../configure --with-ssl=openssl OPENSSL_CFLAGS=-I$VYASA/usr/include OPENSSL_LIBS="-L/usr/lib -lssl -lcrypto"

make -j$(nproc)
make install
cd .. && package $(basename `pwd`)
# ------------------------------
