#!/bin/sh

set -e -u -o pipefail

# zlib
# ------------------------------
cd /builds
rm -rf zlib-1.3.1
tar -xf /sources/zlib-1.3.1.tar.gz
mkdir zlib-1.3.1/build -p
cd zlib-1.3.1/build

../configure --prefix=/usr

make -j$(nproc)
make install
cd .. && package $(basename `pwd`)
# ------------------------------
