#!/bin/sh

set -e -u -o pipefail

# zstd
# ------------------------------
cd /builds
rm -rf zstd-1.5.7/
tar -xf /sources/zstd-1.5.7.tar.gz
cd zstd-1.5.7/

make -j16

make install
# ------------------------------
