#!/bin/sh

set -e -u -o pipefail

# zstd
# ------------------------------
cd /builds
rm -rf zstd-1.5.7/
tar -xf /sources/zstd-1.5.7.tar.gz
cd zstd-1.5.7/

make prefix=/usr -j$(nproc)

make prefix=/usr install
#FIX: package $(basename `pwd`) "prefix=/usr"
# ------------------------------
